name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/my-app:latest .

    - name: sonar qube 
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Scan Docker image
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ghcr.io/${{ github.repository }}/my-app:latest


    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository }}/my-app:latest